version: '3'

services:

  test_mysql:
    restart: always
    container_name: mysql_container
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 12345678
    command: [
      '--character-set-server=utf8mb4', 
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password']
  
  test_phpmyadmin:
    restart: always
    container_name: phpadmin_container
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      PMA_HOST: test_mysql
      MYSQL_ROOT_PASSWORD: 12345678
    depends_on:
      - test_mysql